"""Criando tabela aasgendamentos

Revision ID: 8b86ba3dd965
Revises: f12b32c8b0b2
Create Date: 2025-03-31 18:14:51.218179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b86ba3dd965'
down_revision: Union[str, None] = 'f12b32c8b0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('horario', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('servico', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='agendamentos_pkey')
    )
    # ### end Alembic commands ###
